### ISSUE TITLE
这个chatgpt的api是一个字一个字返回的吗

### ISSUE THREAD

**Issue by Mr-IT007** [ayaka14732/ChatGPTAPIFree#12]
这个chatgpt的api是一个字一个字返回的吗还是一下返回全部文本信息

**Comment by ayaka14732** [comment]
The API endpoint acts as a proxy to the OpenAI upstream API, meaning that it supports the same parameters. You can set `stream: true` in the request object to enable the server to return a streaming response. Note that the API endpoint itself does not modify or process the response in any way, it simply forwards the upstream response back to the client.
