### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by saliksik** [ayaka14732/ChatGPTAPIFree#15]
Hello Ms. Ayaka,

I successfully setup my own instance unfortunately I am having a problem with CORS policy, here are the error messages I am getting from Google Run and web console:

{
httpRequest: {11}
insertId: "640c4eXXXXXXXXXbef81ca15"
labels: {5}
logName: "projects/XXXXX/logs/run.googleapis.com%2Frequests"
receiveTimestamp: "2023-03-11T09:50:XXXXZ"
resource: {2}
severity: "ERROR"
spanId: "4361714022011534635"
textPayload: "The request failed because either the HTTP response was malformed or connection to the instance had an error. Additional troubleshooting documentation can be found at: https://cloud.google.com/run/docs/troubleshooting#malformed-response-or-connection-error"
timestamp: "2023-03-11T09:50:3XXXZ"
trace: "pXXXX14faaa"
}

Access to fetch at 'https://XXXXX.a.run.app/v1/' from origin 'https://aXXXXX.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Response Headers

access-control-allow-headers: Content-Type, Authorization
access-control-allow-methods: GET, HEAD, POST, OPTIONS
access-control-allow-origin: *
alt-svc: h3=":443"; ma=xx29=":443"; ma=2592000,h3-Q0xxx:443"; ma=259xx0,quic=":443"; ma=2592000; v="46,43"
content-length: 9
content-type: text/plain; charset=utf-8
date: Sat, 11 Mar 2023 09:59:10 GMT
server: Google Frontend
x-cloud-trace-context: ef8663xxx533eed

Thank you.

**Comment by ayaka14732** [comment]
This is strange, as the error messaage says no 'Access-Control-Allow-Origin' header is present on the requested resource, but it is presented in the response headers as you show below.

**Comment by saliksik** [comment]
I attempted to redeploy again, ensuring that all the information was accurate, including the MongoDB details, as well as the names of the database and collections. On Cloud Run, I set the authentication to permit unauthenticated access, properly configured the environment variables, established the server to run on port 8080, and set the execution environment to default. Despite these efforts, the error persisted.

**Comment by saliksik** [comment]
Did I miss something? :(

**Comment by ayaka14732** [comment]
Check the response headers and see if the 'Access-Control-Allow-Origin' header is really there

**Comment by saliksik** [comment]
> Check the response headers and see if the 'Access-Control-Allow-Origin' header is really there

I will try again. I will update you. Thank you :)

**Comment by saliksik** [comment]
Dear Ms. Aya,

I am happy to report that the issue has been resolved. As it turns out, I failed to enable access for all networks on my MongoDB. I apologize for the oversight. Thank you for your diligent efforts to assist me throughout this process.
