### ISSUE TITLE
feature: MongoDB Error Handling

### ISSUE THREAD

**Issue by llegomark** [ayaka14732/ChatGPTAPIFree#18]
Hi Ayaka!

I am writing to suggest improving the reliability of the ChatGPTAPIFree by implementing proper error handling for MongoDB connections.

Currently, the code assumes that the connection to MongoDB will always succeed, but there are several reasons why the connection could fail, such as network issues or invalid credentials. As a result, the lack of proper error handling may lead to critical issues, such as data loss or incorrect data processing.

I recommend adding error handling for MongoDB connection failures to address this issue. By doing so, you can improve the reliability of the API and reduce the risk of data loss or incorrect data processing.

Thank you for considering my suggestion.

Sample code:

![Screenshot (170)](https://user-images.githubusercontent.com/111579522/224523104-863372d9-7cf1-4628-b555-9f4d4fd6d3c7.png)

- The MongoClient is created outside the app variable and connected to MongoDB using the connect() method. If an error occurs, the code logs the error and exits the process with an exit code of 1 to indicate a fatal error.
- The MongoDB collection is created, and the indexes are created as before.
- The catch block of the /v1/ route now logs the error to the console before sending a generic error message back to the client.
- This implementation should now handle errors related to MongoDB connections.

```
const client = new MongoClient(uri);
client.connect((err) => {
  if (err) {
    console.error(err);
    process.exit(1);
  } else {
    console.log('Connected successfully to MongoDB at ' + uri);
  }
});
```
```
    resUpstream.body.pipe(res);
  } catch (error) {
    console.error(error);
    res.status(500).set(corsHeaders).type('text/plain').send('Internal server error');
  }
});
```

**Comment by ayaka14732** [comment]
Thank you for your suggestion. Would you mind creating a pull request for that?

**Comment by ayaka14732** [comment]
I think we can remove MongoDB, as is possible to setup rate limit directly using Google Cloud Armor

**Comment by llegomark** [comment]
> Thank you for your suggestion. Would you mind creating a pull request for that?

Done. Thank you :)

**Comment by ayaka14732** [comment]
@llegomark Thank you for your work. Besides, I am exploring using Google Cloud Armor to set up rate limits directly. This will allow us to tailor the rate limit and avoid relying on MongoDB

**Comment by llegomark** [comment]
@ayaka14732 I think using Google Cloud Armor for rate limiting is a good idea. Even though MongoDB can limit the number of requests from specific IP addresses, using Cloud Armor is better when dealing with many IP addresses. It can handle a high volume of traffic and is more dependable. Moreover, using Cloud Armor for rate limiting would remove the necessity of keeping a different database to store rate limit information, making the application's design less complicated.
