### ISSUE TITLE
wrangler.toml

### ISSUE THREAD

**Issue by saliksik** [ayaka14732/ChatGPTAPIFree#2]
Hi Ma'am Ayaka!

Thank you for this. Hoping you can help me how to set up the wrangler.toml properly since I have multiple Cloudflare accounts connected to my main CF account.

Let's say I wanted to use the AAA account.

Thank you :)

✘ [ERROR] More than one account available but unable to select one in non-interactive mode.

If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
  Please set the appropriate `account_id` in your `wrangler.toml` file.
  Available accounts are (`<name>`: `<account_id>`):
    `AAA`: `ece12a4fbc7b131fc17d118`
    `BBB`: `c1b0fa2f2e392fd5dbbca5e3e`
    `CCC`: `04ecf3126ab6a336d11c[25](https://github.com/xxxxx/actions/runs/43xxjobs/756xx756#step:5:26)7d4c746116`
    `DDD`: `f618f8ef0557ef4d9c898c6c[26](https://github.com/xxxxx/actions/runs/43xx0380/jobs/7xx56#step:5:27)7821a`
    `EEE`: `5f1d81df6a7ba9461f756a8faeb34[29](https://github.com/xxxxx/actions/runs/4xxx0/jobs/75xx56#step:5:30)`

**Comment by ayaka14732** [comment]
I believe that this can be done by setting `account_id` in the `wrangler.toml` file, according to the documentation (https://developers.cloudflare.com/workers/wrangler/configuration/)

Let's say if you want to use account AAA, just set:

```toml
account_id = ece12a4fbc7b131fc17d118
```

**Comment by saliksik** [comment]
Thank you, Ma'am Ayaka! I have just added the API key as JSON. It is now functioning properly.
