### ISSUE TITLE
Hi! Boss!

### ISSUE THREAD

**Issue by Ming-XF** [ayaka14732/ChatGPTAPIFree#20]
As I am a personal developer, Open AI recharge is not supported in my area, and my personal free API account has been banned recently, so this project is of great help to me! I hope it can survive for a long time. As a student, I don't have a lot of money, but I have contributed some small money to you, hoping to help this project. If you can't stick to this free project, I hope I can pay for it. Please let me know before you finish this project. Thank you. Sincerely Ming-XF.

**Comment by ayaka14732** [comment]
Thank you so much for your generous contribution and kind words of support. It means a lot to me to hear how my work is making a positive impact in the lives of personal developers like you. I am committed to keeping this project available for as long as possible. I will make sure to keep you informed if anything changes.

**Comment by yiiing** [comment]
免费的白嫖太多了
我希望能增加签名机制。付费使用

**Comment by yiiing** [comment]
方便那些不支持 不方便使用接口的开发者。
