### ISSUE TITLE
api fees should run out

### ISSUE THREAD

**Issue by zjrwtx** [ayaka14732/ChatGPTAPIFree#25]
![image](https://user-images.githubusercontent.com/86822589/225322140-6747657c-63cc-4cad-b05c-761feed2db21.png)

**Comment by ayaka14732** [comment]
I have increased the limit, and API access should be reinstated shortly. However, we are soon running out of fee. In this case, considering the use of New Bing could be a good idea, especially because it is powered by the more advanced GPT-4 model.

See #5

**Comment by zjrwtx** [comment]
> I have increased the limit, and API access should be reinstated shortly. However, we are soon running out of fee. In this case, using New Bing could be a good idea, especially because it is powered by the more advanced GPT-4 model.
> 
> See also #5

all right, thanks

**Comment by manm15** [comment]
We should use text-curie-001
