### ISSUE TITLE
How to Support?

### ISSUE THREAD

**Issue by HarshNarayanJha** [ayaka14732/ChatGPTAPIFree#30]
Just saw this amazing initiative. I really wanted to try out ChatGPT, but I didn't have a Phone Number. Now I can experiment with it. Thanks very much.

I do want to support this project, but I can't financially, sorry. But I am a student learning developing/programming, and probably can help with anything you want.

Just tell me 😉

**Comment by mediaexplorer74** [comment]
Hi ) Yes, amazing initiative.  As [HarshNarayanJha](https://github.com/HarshNarayanJha), I cannot register&use original ChatGPT for some "world politics" reasons. 
Yesterday I noticed that ChatGPTAPIFree cannot connect to OpenAI service due some magic limits (zero quota?). So, no success.
But I'm old and experienced developer. Plan B is:
- VPN on;
- Open Edge browser, go Settings, choose U.S. region;
- Go bing.com/new

Cheers up,
[M]edia[E]xplorer

**Comment by HarshNarayanJha** [comment]
> magic limits (zero quota?)

No magic limits, but @ayaka14732 is paying himself for all of us. So there is no surprise for this kind of message.

**Comment by mediaexplorer74** [comment]
> > magic limits (zero quota?)
> 
> No magic limits, but @ayaka14732 is paying himself for all of us. So there is no surprise for this kind of message.

Ok, I see (undestand).
But main theme (issue) says: "How to Support?" So, how you support (solve) the problem? There is many ways. What's is your way? You may do scanning "demo keys" on all Github "storage", for example:
https://github.com/search?q=OPENAI_API_KEY+sk-&type=code

**Comment by HarshNarayanJha** [comment]
Searched them but are all "invalid" keys, and i guess there is no meaning in looking on youtube too...

**Comment by mediaexplorer74** [comment]
> Searched them but are all "invalid" keys, and i guess there is no meaning in looking on youtube too...

Uhhh.... bad news. Ok, some foreign user's help needed to register normal api key :(

**Comment by pilgrimlyieu** [comment]
[你可以回复我吗](https://www.baidu.com)

**Comment by ayaka14732** [comment]
Thank you so much for your kind words and enthusiasm for ChatGPTAPIFree! No need to worry about financial support. You can still make a significant impact by helping to spread the word about ChatGPTAPIFree. One of the best ways to support us is by telling others who might be interested in the project and encouraging them to consider sponsoring or contributing. I am excited to have you as part of the ChatGPTAPIFree community!
