### ISSUE TITLE
How it possible test any integration without limitation? 

### ISSUE THREAD

**Issue by blackPantherOS** [ayaka14732/ChatGPTAPIFree#32]
Free with limited quota? I think so this is not free, just trial.

```
OpenAI API responded:

{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
```

**Comment by yiiing** [comment]
Need to recharge
The interface is not free

**Comment by ayaka14732** [comment]
This is error message is responded by OpenAI, indicating that there was insufficient balance in my account. I have recharged it just now, and the issue should be resolved.

Besides, if you want to test the API, you can test it by providing your own API key. In this case, the API serves as a proxy, and your API key will not be saved on the server.
