### ISSUE TITLE
access_terminated

### ISSUE THREAD

**Issue by xodn** [ayaka14732/ChatGPTAPIFree#38]
Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.

The above error occurs when I use。

**Comment by Moth-6** [comment]
it seems that OpenAI's policy prohibits sharing API Keys.
under section 2. (c). (vii). of the Terms of use
https://openai.com/policies/terms-of-use#:~:text=(vii)%20buy%2C%20sell%2C%20or%20transfer%20API%20keys%20without%20our%20prior%20consent%3B

**Comment by xodn** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by denene12** [comment]
this is a problem here

**Comment by foxe6** [comment]
RIP

**Comment by LyubomirT** [comment]
> it seems that OpenAI's policy prohibits sharing API Keys. 😞 under section 2. (c). (vii). of the Terms of use it isn't very clear since "buy, sell, or transfer API keys without our prior consent" doesn't necessarily mean sharing API keys for free is also restricted. but it surely can be interpreted as such, especially if it is something that's going to hurt OpenAI's profitability. https://openai.com/policies/terms-of-use#:~:text=(vii)%20buy%2C%20sell%2C%20or%20transfer%20API%20keys%20without%20our%20prior%20consent%3B

Perhaps OpenAI noticed this, and considered the project as "affecting their profitability". But I don't think so, because, even though the project is free for everyone, OpenAI **does** get profit from it. Forgive me if I'm wrong.

**Comment by Moth-6** [comment]
Yes that‘s just a presumption. There might be other reasons why the accounts get suspended.

**Comment by katjap** [comment]
oh that sucks. i just discovered this project just now. >_<

**Comment by LyubomirT** [comment]
> oh that sucks. i just discovered this project just now. >_<

Something like that happened with vicgalle's GPT-J API, when I just found out it exists 😥

**Comment by GlitchedCloud** [comment]
Any idea when this will be resolved? How can we provide support? Are there similar alternatives in the meantime?
I need access to a chatbot API for an upcoming school project (super small scale prototype).

**Comment by ayaka14732** [comment]
> I need access to a chatbot API for an upcoming school project

For this, I think you can just register an OpenAI account and use your own API

**Comment by GlitchedCloud** [comment]
> > I need access to a chatbot API for an upcoming school project
> 
> For this, I think you can just register an OpenAI account and use your own API

I cannot. I do not have phone number to register. I've tried, but cannot get the text to my country. 😞
Thanks for doing this project though, it looks awesome!

**Comment by LyubomirT** [comment]
> > > I need access to a chatbot API for an upcoming school project
> > 
> > 
> > For this, I think you can just register an OpenAI account and use your own API
> 
> I cannot. I do not have phone number to register. I've tried, but cannot get the text to my country. 😞 Thanks for doing this project though, it looks awesome!

Co:here doesn't require a phone number, just an email. Perhaps you can use it?

**Comment by GlitchedCloud** [comment]
> > > > I need access to a chatbot API for an upcoming school project
> > > 
> > > 
> > > For this, I think you can just register an OpenAI account and use your own API
> > 
> > 
> > I cannot. I do not have phone number to register. I've tried, but cannot get the text to my country. 😞 Thanks for doing this project though, it looks awesome!
> 
> Co:here doesn't require a phone number, just an email. Perhaps you can use it?

Interesting... Thanks so much!

**Comment by LyubomirT** [comment]
> > > > > I need access to a chatbot API for an upcoming school project
> > > > 
> > > > 
> > > > For this, I think you can just register an OpenAI account and use your own API
> > > 
> > > 
> > > I cannot. I do not have phone number to register. I've tried, but cannot get the text to my country. 😞 Thanks for doing this project though, it looks awesome!
> > 
> > 
> > Co:here doesn't require a phone number, just an email. Perhaps you can use it?
> 
> Interesting... Thanks so much!

You're welcome! It's free to use, with only one restriction - not more than 5 messages/minute.

**Comment by ayaka14732** [comment]
I have created another paid account, and the service should be resumed now.
