### ISSUE TITLE
OpenAI API responded: { "error": { "message": "Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.", "type": "access_terminated", "param": null, "code": null } }

### ISSUE THREAD

**Issue by itsbgold** [ayaka14732/ChatGPTAPIFree#42]
Please fix this
OpenAI API responded: { "error": { "message": "Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.", "type": "access_terminated", "param": null, "code": null } }

**Comment by ayaka14732** [comment]
I have emailed OpenAI via email to ask for a justification for terminating my API keys. If I do not receive a response, I reserve my rights to withhold the payment for the fees that have already been incurred. It is important for me to understand the situation and receive a satisfactory explanation before moving forward with any further transactions.

**Comment by Moth-6** [comment]
/#38

**Comment by CoderQCFromScraatch** [comment]
will this project be revived?

**Comment by LyubomirT** [comment]
> will this project be revived?

Nobody knows, but I hope so.

**Comment by ayaka14732** [comment]
I'm pursuing every possible avenue to revive this project and make it freely accessible to everyone.

**Comment by ayaka14732** [comment]
I have created another paid account, and the service should be resumed now.
