### ISSUE TITLE
Unable to connect to Free ChatGPT

### ISSUE THREAD

**Issue by JiaxiangBU** [ayaka14732/ChatGPTAPIFree#43]
Description: I am unable to access the Free ChatGPT website at <https://freechatgpt.chat/>. The page is taking too long to load and seems unresponsive. I have tried accessing it multiple times, but the issue persists. I suspect it's not a network issue on my end.

Steps to reproduce:

1.  Visit <https://freechatgpt.chat/>

2.  Try to connect with valid credentials

3.  Observe the slow loading and unresponsiveness of the page

I have tried accessing the website from different devices and networks, but the issue remains the same. Kindly assist in resolving this issue.

Thank you.

**Comment by ztjhz** [comment]
Hi, the website at https://freechatgpt.chat/ has been blocked in mainland China. You can consider using mirror sites or hosting your own version of the site by following the deployment instructions [here](https://github.com/ztjhz/FreeChatGPT/blob/main/README.md).

**Comment by yaoshanliang** [comment]
> Hi, the website at https://freechatgpt.chat/ has been blocked in mainland China. You can consider using mirror sites or hosting your own version of the site by following the deployment instructions [here](https://github.com/ztjhz/FreeChatGPT/blob/main/README.md).

Which mirror site?

**Comment by JiaxiangBU** [comment]
> Hi, the website at https://freechatgpt.chat/ has been blocked in mainland China. You can consider using mirror sites or hosting your own version of the site by following the deployment instructions [here](https://github.com/ztjhz/FreeChatGPT/blob/main/README.md).

Thanks for your reply, I work out the mirror for me. But there is another question

```
export default defineConfig({
  base: '/REPO/',
  /* Rest of the configuration here */
});
```

I'm having trouble with the base path configuration for my website. According to the instructions, I should set `base: '/REPO/'` in my configuration file, but doing so results in a blank page. However, when I set the value to `base: '/FreeChatGPT/'`, the website works as expected.

I'm not very familiar with JavaScript and was wondering if `REPO` is some sort of variable or if it's just a relative path. I'd appreciate any insight on this.

Also, I would like to know how to set the website in Mandarin.

Thank you for your help.

(Maybe should I make a new issue?)

**Comment by ayaka14732** [comment]
@JiaxiangBU Yes, `/REPO/` should be `/FreeChatGPT/`. I will update the README to make it clear.

The language of the website should be automatically determined based on the user's browser setting.

**Comment by JiaxiangBU** [comment]
> The language of the website should be automatically determined based on the user's browser setting.

Maybe I do not know how to fix it, can I customize it manually? Thank you for your feedback!

**Comment by ztjhz** [comment]
Hi, you can pull the latest changes to your fork. This should fix your issue.
