### ISSUE TITLE
Are you okay?

### ISSUE THREAD

**Issue by code-yeongyu** [ayaka14732/ChatGPTAPIFree#6]
Because you are literally paying for others without any rewards. I am thankful about it, but just concerning: are you okay?

**Comment by fakellgit** [comment]
I wonder too, it's too nice of him🥺

**Comment by ayaka14732** [comment]
The free API is not operational at the moment. The current cost for using the API is $155.72 per day, and it seems unfeasible to sustain the API service without a substantial donation

My ultimate goal is to make ChatGPT more easily accessible to a wider audience, particularly those who lack technical expertise, and enable them to experience the benefits of technological advancement.

To achieve this, I propose developing small-scale API backends for sharing among a small group of people. These backends would be set up by a technically proficient person and then shared among their friends. On the freechatgpt.chat website, people can access the ChatGPT API using these API endpoints.

If many technically proficient people adopt this approach, more people will be able to access ChatGPT.

**Comment by Weblure** [comment]
Unfortunate, but unsurprising. You could spread it out more fairly by implementing a token and rate limit, but I don't see this ever being scalable without running ads or something to fund it.

**Comment by eatcosmos** [comment]
> Unfortunately, the free API is not operational at the moment. The current cost for using the API is $155.72 per day, and it seems unfeasible to sustain the API service without a substantial donation.

估计被很多二手API贩子拿去做按条收费的saas api封装服务了，不然个人请求量不会这么大
It is estimated that many second-hand API dealers have taken it to do per-charge saas api packaging services, otherwise personal requests will not be so large.
